name: Build Image

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  buildx:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target-cloud: ["gcp-aws", "azure"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Build
        run: |
          docker build --target ${{ matrix.target-cloud }} --tag mlflow:latest-${{ matrix.target-cloud }} --load .

      - name: Container image scan
        uses: Azure/container-scan@v0.1
        continue-on-error: true
        env:
          DOCKLE_HOST: "unix:///var/run/docker.sock" # https://github.com/aquasecurity/trivy/issues/2432#issuecomment-1172432975
        with:
          image-name: mlflow:latest-${{ matrix.target-cloud }}
