name: Build Image

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Build (standard)
        run: |
          docker build --tag mlflow:latest --load ./standard

      - name: Build (appengine)
        run: |
          docker build --tag mlflow:latest-appengine --load ./appengine

      - name: Container image scan (standard)
        uses: Azure/container-scan@v0.1
        with:
          image-name: mlflow:latest

      - name: Container image scan (appengine)
        uses: Azure/container-scan@v0.1
        with:
          image-name: mlflow:latest-appengine