name: Build Image

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Build (standard)
        run: |
          docker build --tag docker.io/library/mlflow:standard --load ./standard

      - name: Build (appengine)
        run: |
          docker build --build-arg BASE_IMAGE=docker.io/library/mlflow:standard --tag docker.io/library/mlflow:appengine --load ./appengine

      - name: Container image scan (standard)
        uses: Azure/container-scan@v0.1
        with:
          image-name: docker.io/library/mlflow:standard
          severity-threshold: CRITICAL

      - name: Container image scan (appengine)
        uses: Azure/container-scan@v0.1
        with:
          image-name: docker.io/library/mlflow:appengine
          severity-threshold: CRITICAL