name: Build & Publish Image

on:
  push:
    tags:
      - '*.*.*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Build
        run: |
          docker build --tag mlflow:latest --build-arg MLFLOW_VERSION=$RELEASE_VERSION  --load .

      - name: Publish Image (version)
        uses: mattes/gce-docker-push-action@v1
        with:
          creds: ${{ secrets.PUBLIC_GCR_DEPLOY_SA_KEY }}
          src: mlflow:latest
          dst: gcr.io/getindata-images-public/mlflow:${{ env.RELEASE_VERSION }}

      - name: Publish Image (latest)
        uses: mattes/gce-docker-push-action@v1
        with:
          creds: ${{ secrets.PUBLIC_GCR_DEPLOY_SA_KEY }}
          src: mlflow:latest
          dst: gcr.io/getindata-images-public/mlflow:latest
